spring:
  datasource:
    url: # jdbc:mysql://{접속할 IP}:3306/{DB 이름}?characterEncoding=UTF-8
    username: # DB 접속할 계정 USERNAME
    password: # DB 접속할 계정 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          # OAuth2
          facebook:
            client-id: # 생략
            client-secret: # 생략
            scope:
              - public_profile
              - email

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# 프로필/게시물 사진 파일 업로드 경로 설정
# 로컬 테스트 시
#profileImage:
#  path: C:/workspaces/project/profile/
#post:
#  path: C:/workspaces/project/upload/

# 배포 시
profileImage:
  path: /home/ubuntu/profile/
post:
  path: /home/ubuntu/upload/
